apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-wait-vpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busy-wait-vpa
  template:
    metadata:
      labels:
        app: busy-wait-vpa
    spec:
      containers:
      - name: busy-wait-vpa
        image: kewynakshlley/busy-wait-noclustering #slave-leech
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 150m
            memory: 75Mi
          limits:
            cpu: 1500m
            memory: 225Mi
        ports:
        - containerPort: 3000

