apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: busy-wait-vpa
spec:
  selector:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: busy-wait-vpa
  updatePolicy:
    updateMode: "Auto"


